version: '3.7'
services:
  jupyterlab:
    image: syunyooo/pytorch-nvidia-jupyterlab
    ports:
      - 80:8888
    volumes:
      - ./:/root/user/work
    working_dir: /root/user/work
    command: sh /run.sh
    restart: always
  tensorboard:
    build: env/tensorboard
    volumes:
      - ./logs:/logs
    working_dir: /logs
    ports:
      - 6006:6006
    environment:
      reload_interval: 2
      log_dir: /logs
    privileged: true
    restart: always
